# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
    
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.6.0

    - name: Set up JDK 9
      uses: actions/setup-java@v2
      with:
        java-version: '9'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Grant execute permission for gradlew-wrapper
      run: chmod +x gradle/wrapper/gradle-wrapper.jar
      
    - name: Build with Gradle
      run: ./gradlew build

 
